"""add brand table

Revision ID: 507777bcd616
Revises: f5c9b3b7eb2f
Create Date: 2022-05-07 19:47:36.866270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507777bcd616'
down_revision = 'f5c9b3b7eb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
        sa.Column('id', sa.CHAR(36), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('about', sa.Text(), nullable=True),
        sa.Column('social_media', sa.String(length=256), nullable=True),
        sa.Column('website', sa.String(length=256), nullable=True),
        sa.Column('email', sa.String(length=128), nullable=True),
        sa.Column('phone', sa.String(length=128), nullable=True),
        sa.Column('created_time', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
        sa.Column('owner', sa.CHAR(32), nullable=True),
        sa.ForeignKeyConstraint(['owner'], ['user.id'], name='fk_brand_user_id_owner', onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('owner', 'name', name='uc_brand_owner_name')
    )
    op.create_index(op.f('ix_brand_id'), 'brand', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_id'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
