"""add product table

Revision ID: 93593486a310
Revises: 507777bcd616
Create Date: 2022-05-08 17:00:25.573162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93593486a310'
down_revision = '507777bcd616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
        sa.Column('id', sa.CHAR(36), nullable=False),
        sa.Column('title', sa.String(length=128), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('discount_rate', sa.Float(), nullable=False),
        sa.Column('image', sa.LargeBinary(length=20000000), nullable=True),
        sa.Column('created_time', sa.DateTime(), nullable=True),
        sa.Column('brand', sa.CHAR(36), nullable=True),
        sa.ForeignKeyConstraint(['brand'], ['brand.id'], name='fk_product_brand_id_brand', onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('brand', 'title', name='uc_product_brand_title')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
